# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a5a92fdca88cf9c60e6234df9db045b418afdedb6cf7f5dc287cf748032ef506d98aea9a5eb0d9c8b7850d10d69f7c2fc4972ba0a93293d50645df6b81112f5

test:
  secret_key_base: c7b5296fde0056ec738775129891ab16e2b9048199fcbccdf24ff9ff7226f453d083e92bdea06866ca195cc439b1d2b1317984499aff10e4e94e0ea6cad7fe88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
